spring:


  datasource:
    url: jdbc:mariadb://localhost:43306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: simDev1234@gmail.com
    password: jrtrukjjnihmphqz
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          starttls:
            enable: true
logging:
  level:
    root: debug

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl